apiVersion: v1
kind: Secret

metadata:
  name: cloudmon-secret
  namespace: cloudmon

type: Opaque

stringData:

  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: cloudmon
  DATABASE_USER: cloudmon_user
  DATABASE_PASSWORD: CHANGE_ME
